### ISSUE TITLE
Multithreading is unsafe when  call k_nearest_neighbors()  method

### ISSUE THREAD

**Issue by zuixiaosanlang** [cdalitz/kdtree-cpp#3]
i want to query k_nearest_neighbors by Multithreading,
any suggest？
thanks

**Comment by cdalitz** [comment]
You are right that this function is not thread safe. This is because it stores the points collected during the search in the member variable `KdTree:neighborheap` which leads to conflicts when `k_nearest_neighbors()` is called in parallel with itself or the other search function.

It should be no problem to fix this by making `neighborheap` a local variable in the search functions. This requires a thorough testing, though, to make sure that the search still works and the function is actually thread safe after this change.

Feel free to make this change, test it and submit it as a pull request. Thanks, Christoph

**Comment by zuixiaosanlang** [comment]
@cdalitz 
do as you say, it is ok now.
thanks

![image](https://user-images.githubusercontent.com/20105627/188360312-b2eb1262-ba7a-4618-ac3e-de45398722b3.png)

**Comment by cdalitz** [comment]
This is now fixed in the new release version 1.2.
